### ISSUE TITLE
Please, post screenshots ASAP

### ISSUE THREAD

**Issue by braian87b** [iptux/DroidUi#6]
there is no screenshot or video on google nor youtube, please take a few and upload it here!

**Comment by iptux** [comment]
Why are you expecting any support from a project which is inactive for more than two years?

**Comment by braian87b** [comment]
May be If you were uploaded those... just joking, never its too late to relive an old project.

**Comment by ratulrafsan** [comment]
The sl4a project has been inactive for the last 7 years. There's no point in reviving this project.
If you don't like Java then go for kotlin, it's "" kind of"" simpler than java.

**Comment by braian87b** [comment]
I'd go for C# Xamarin... seems much better than shitty java...
